// <auto-generated />
namespace DemoRealEstate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateval : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateval));
        
        string IMigrationMetadata.Id
        {
            get { return "202210051230135_update-val"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
