// <auto-generated />
namespace DemoRealEstate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addrequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrequest));
        
        string IMigrationMetadata.Id
        {
            get { return "202210040834203_add-request"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
